# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-01 11:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0003_auto_20171101_0907'),
    ]

    operations = [
        migrations.AlterField(
            model_name='items',
            name='ID',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
